# This is a basic workflow to help you get started with Actions

name: CI

on:
  create:
    tags: [ "*" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create ansible vault password file
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
        run: echo ${VAULT_PASS} > .vault-pass

      - name: Install Node dependencies
        run: make install

      - name: Build application
        run: make build
        
      - name: Build nginx docker image
        env:
          RELEASE: ${{ env.GITHUB_RUN_ID }}
        run: make build_nginx_image
        
      - name: Save nginx docker image as tar.gz file
        env:
          RELEASE: ${{ env.GITHUB_RUN_ID }}
        run: make save_nginx_image
        
      - name: Build ansible docker image
        run: make build_ansible_image
        
      - name: Deploy application
        env:
          RELEASE: ${{ env.GITHUB_RUN_ID }}
        run: make deploy
