name: CI

on:
  create:
    tags: [ "*" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create ansible vault password file
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
        run: echo ${VAULT_PASS} > .vault-pass

      - name: Install Node dependencies
        run: make install_frontend

      - name: Build application
        run: make build_frontend
        
      - name: Build nginx docker image
        run: make build_nginx_image RELEASE=$GITHUB_RUN_ID
        
      - name: Save nginx docker image as tar.gz file
        run: make save_nginx_image RELEASE=$GITHUB_RUN_ID
        
      - name: Build ansible docker image
        run: make build_ansible_image
        
      - name: Deploy application
        run: make deploy RELEASE=$GITHUB_RUN_ID
